### ISSUE TITLE
缺失文件

### ISSUE THREAD

**Issue by hhf-hd** [ernie-research/gptfluence#1]
![image](https://github.com/user-attachments/assets/61a6f92f-57a0-4914-af80-fac9fbd9f268)

你好，好像缺失了这两个文件，能不能加上呢，非常感谢！

**Comment by hhf-hd** [comment]
测试文件好像可以直接运行test.py，方便阐述下这些参数的意义吗？尤其是task 和dataset_name好像有些混淆，非常感谢！

**Comment by cyk1337** [comment]
CC @DwyaneLQY
